# Generated by Django 4.1.7 on 2023-04-12 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_useraddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAddress',
        ),
    ]
