# Generated by Django 4.1.7 on 2023-04-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_alter_usermodel_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(blank=True, default='password', max_length=50, null=True),
        ),
    ]
